import config from "config";
import { getAllPosts } from "helpers/contentRender";
import type { NextPage } from "next";
import Head from "next/head";

import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Intro from "@/components/Intro";
import Pagination from "@/components/Pagination";
import Posts from "@/components/Posts";
import StandWithUkraine from "@/components/StandWithUkraine";
import Tags from "@/components/Tags";

export type Post = {
  slug: string;
  title: string;
  date: string;
  featuredImage: string;
  draft: boolean;
  tags: string[];
};

type Props = {
  posts: Post[];
};

const Home: NextPage<Props> = ({ posts }: Props) => (
  <>
    <Head>
      <title>{config.site_title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <StandWithUkraine />
    <Header />
    <Intro />
    <section className="simple-section">
      <div className="container">
        <Tags />
        <Posts posts={posts} />
        <Pagination />
      </div>
    </section>
    <Footer />
  </>
);

export const getStaticProps = async () => {
  const posts = getAllPosts([
    "slug",
    "title",
    "featuredImage",
    "date",
    "draft",
    "tags",
  ]).filter((post: Post) => post.draft === false);

  return {
    props: { posts },
  };
};

export default Home;
